### ISSUE TITLE
Search Functionality broken currently

### ISSUE THREAD

**Issue by hzyniecki** [softsimon/ngx-bootstrap-multiselect#471]
When the search setting is enabled, if you search for an invalid item you'll be shown an error message. The problem is this removes your ability to search for anything else since the search disappears from the dropdown. Also ran into an issue when searching for an item in the dropdown, successfully finding and selecting the item; this would make all the other items in the dropdown disappear even after unselecting the selected item... The search also disappeared in this scenario as well!

**Comment by LukeMcDonnell** [comment]
Running into the same problem. Any fix for this? Using angular 11, latest version on ngx-bootstrap-multiselect

**Comment by LukeMcDonnell** [comment]
Ok I thought I was on the latest version because github releases page reports v2.1 as most recent, however it looks like there's a version mis-match and the latest is actually 2.1.1:
![image](https://user-images.githubusercontent.com/15354254/110196155-384ba400-7e8a-11eb-944e-26aa674fde67.png) 

![image](https://user-images.githubusercontent.com/15354254/110196182-64672500-7e8a-11eb-9d09-b8c9e2d5fbe9.png)

Running `npm install ngx-bootstrap-multiselect@2.1.1` resolved the issue.

**Comment by hzyniecki** [comment]
Lukes response fixed the issues, closing.
